version: 2
updates:
  - package-ecosystem: "npm"
    target-branch: "main"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      minor-updates:
        update-types: ['patch', 'minor']
        applies-to: 'version-updates'
    cooldown:
      default-days: 7
